# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4f81b4fb57eb096f6d7aa2e5d4a1f8276ef2cd320264cc1d422b4326b67a90842325c560d0314ae9fadeb0d14da50bf7a6ae7c4714bd1e54415fa39ee1e602

test:
  secret_key_base: 471155968e7f41c7d147862f11977940cff8e21624d4206166b9bdcfa01554a6bfb13e2c9794667955a04f39ec17c9dfa86634edbf4c6f0fc945e7ef6188749b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
